/*
 * main.c
 * ------
 * Entry point of the MiniLang compiler.
 * Reads the source file, runs the lexer and parser,
 * and evaluates the resulting AST.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lexer.h"
#include "ast.h"
#include "parser.h"
#include "evaluator.h"

static char* read_file(const char* filepath) {
    FILE* file = fopen(filepath, "rb");
    if (!file) {
        fprintf(stderr, "Error: could not open file '%s'\n", filepath);
        return NULL;
    }

    fseek(file, 0, SEEK_END);
    long length = ftell(file);
    fseek(file, 0, SEEK_SET);

    char* buffer = (char*)malloc(length + 1);
    if (!buffer) {
        fprintf(stderr, "Error: out of memory reading file '%s'\n", filepath);
        fclose(file);
        return NULL;
    }

    size_t read_bytes = fread(buffer, 1, length, file);
    buffer[read_bytes] = '\0';
    fclose(file);

    return buffer;
}

static void print_usage(const char* program_name) {
    printf("MiniLang Interpreter (College C Project)\n");
    printf("Usage:\n");
    printf("  %s <source_file.ml> [options]\n\n", program_name);
    printf("Options:\n");
    printf("  --dump-ast     Print AST before executing\n");
    printf("  --compact-ast  Print compact single-line AST format\n");
    printf("  --tokens       Print all tokens generated by lexer\n");
    printf("  --help         Display this help message\n");
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    const char* filepath = NULL;
    int dump_ast = 0;
    int compact_ast = 0;
    int dump_tokens = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--dump-ast") == 0) {
            dump_ast = 1;
        } else if (strcmp(argv[i], "--compact-ast") == 0) {
            compact_ast = 1;
        } else if (strcmp(argv[i], "--tokens") == 0) {
            dump_tokens = 1;
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else if (argv[i][0] != '-') {
            filepath = argv[i];
        } else {
            fprintf(stderr, "Warning: unknown option '%s'\n", argv[i]);
        }
    }

    if (!filepath) {
        fprintf(stderr, "Error: no input file provided\n");
        print_usage(argv[0]);
        return 1;
    }

    char* source = read_file(filepath);
    if (!source) {
        return 1;
    }

    // Optional: Dump Tokens
    if (dump_tokens) {
        printf("=== Lexer Tokens ===\n");
        Lexer token_lexer;
        lexer_init(&token_lexer, source);
        while (1) {
            Token tok = lexer_next_token(&token_lexer);
            printf("Line %-3d | Type: %-15s | Lexeme: '%s'\n",
                   tok.line, token_type_to_string(tok.type), tok.text);
            if (tok.type == TOKEN_EOF || tok.type == TOKEN_ERROR) break;
        }
        printf("====================\n\n");
    }

    // Pipeline: Lexer -> Parser -> AST
    Lexer lexer;
    lexer_init(&lexer, source);

    Parser parser;
    parser_init(&parser, &lexer);

    ASTNode* program = parse_program(&parser);

    if (parser.has_error) {
        fprintf(stderr, "Compilation failed due to syntax errors.\n");
        if (program) ast_free(program);
        free(source);
        return 1;
    }

    // Optional: Visual AST Output
    if (compact_ast) {
        printf("AST: ");
        for (int i = 0; i < program->data.block.count; i++) {
            ast_print_compact(program->data.block.statements[i]);
            if (i + 1 < program->data.block.count) printf("; ");
        }
        printf("\n");
    }

    if (dump_ast) {
        printf("=== Abstract Syntax Tree (AST) ===\n");
        ast_print(program);
        printf("==================================\n\n");
    }

    // Pipeline: Evaluator -> Output
    evaluate(program);

    // Free all allocated memory
    ast_free(program);
    free(source);

    return 0;
}